{% set version = "v2.0rc10" %}
#{% set version = "9ad04607" %}
#this commit should include config search path
#{% set version = "f9d5bd97" %}

package:
  name: bigdatascript
  version: {{ version }}
  #version: "v2.0+{{ version }}"

source:
  git_rev: {{ version }}
  git_url: https://github.com/pcingola/BigDataScript

build:
  number: 0
  skip: False

requirements:
  build:
    - openjdk >=8
    - ant
    - go
  run:
    - openjdk >=8

test:
  commands:
    - "bds -version 2>&1 | grep Bds"

about:
  home: "http://pcingola.github.io/BigDataScript"
  license: Apache 2.0
  summary: "A simple script-language for 'Big Data' piplines."
