{% set version = "v3.1" %}
#{% set version = "9ad04607" %}
#this commit should include config search path
#{% set version = "f9d5bd97" %}

#https://github.com/adoptium/temurin16-binaries/releases/download/jdk16u-2021-07-31-01-01-beta/OpenJDK16U-debugimage_x64_mac_hotspot_2021-07-30-23-30.tar.gz
#
package:
  name: bigdatascript
  version: {{ version }}
  #version: "v2.0+{{ version }}"

source:
  git_rev: {{ version }}
  git_url: https://github.com/pcingola/bds

build:
  number: 0
  skip: False

requirements:
  build:
    - ant
    - go

test:
  commands:
    - "bds -version 2>&1 | grep Bds"

about:
  home: "http://pcingola.github.io/BigDataScript"
  license: Apache 2.0
  summary: "A simple script-language for 'Big Data' piplines."
